<Bx.Chip
    contact-color="${1:red|teal|deep-purple}"
    deletable
    id="$2"
    label="$3"
    onClick={${4:handleClick}}
    onClickDeletable={${4:handleDelete}}>
    <Bx.Icon>
        ${4:person|cloud}
    </Bx.Icon>
</Bx.Chip>